### PR TITLE
Close db connections JENKINS-21058

### PR DESCRIPTION
**Pull request by ricardogarfe**
Use one SessionFactory instead of create one per saved Job:
* [JENKINS-21058](https://issues.jenkins-ci.org/browse/JENKINS-21058)

### CODE REVIEW

**Comment by TimeInvestor** [comment]
Can any one help merge this pull request asap?
Because of this DB connection issue we have to stop using this plugin.

**Comment by ricardogarfe** [comment]
Is working with the same issues, I have to rollback :cry: and try another approach.
Any help will be appreciated.

PS: This plugin is _abandoned_ by its owner. They are looking for a maintainer.

**Comment by TimeInvestor** [comment]
Hi Ricardo García Fernández,
Can you share with me how to use your code to get a working version?

**Comment by sergueik** [comment]
Hello TimeInvestor 
I used to modify java code and build and run hpi of audit2db (few years ago), and may  be interested to help resurrecting it. https://github.com/sergueik/audit2db-plugin

Please let me know if you want to collaborate on this

**Comment by TimeInvestor** [comment]
Hi Serguei Kouzmine,
Glad to work with you. :smiley:
I have raised a pull request to your fork. Pls take a look.
https://github.com/sergueik/audit2db-plugin/pull/1

**Pull request closed without merging**
