### PR TITLE
Adapt icon path removal from core

### PR DESCRIPTION
**Pull request by NotMyFault**
The change proposed prepares the plugin for the icon path removal from core in the upcoming LTS line. This change affects plugins not using the icon API or relying on paths. Plugins using the API properly in the first place are unaffected by this change.

Could you trigger a release after merging this PR please, giving people a chance to update the plugin before updating to the next LTS version @sergueik  
Thanks in advance!

### CODE REVIEW

**Comment by NotMyFault** [comment]
Any chance you could take care of this PR and cut a release? The next LTS baseline selection is currently ongoing @sergueik

**Comment by sergueik** [comment]
Hello Alexander

The change in question looks somewhat cosmetic to me, unfortunately i am not sure i have working Jenkins environment to run and make sure the passing tests - i remember not all tests been successful after conversion to pipeline super classes. Do you have any *Java* code feature request that would justify diving into that project after it being stale for many years ?

Thanks 

Serguei Kouzmine
     On Saturday, April 30, 2022, 07:18:52 AM EDT, Alexander Brandes ***@***.***> wrote:  
 
 


Any chance you could take care of this PR and cut a release? The next LTS baseline selection is currently ongoing @sergueik

**Comment by NotMyFault** [comment]
The change proposed makes sure your icons don't break on the next LTS baseline, because you aren't using the appropriate API but rely on path of the icon.
Considering views in Jenkins are commonly done in Jelly and not in Java, this change affects the appropriate Jelly file and no Java file.

**Comment by sergueik** [comment]
thanks for the feedback Alexander

What i tried to say i can merge the change but i will not be able to run tests and have passed. I understand what templates and Jelly in particular , is :-)

Serguei Kouzmine

     On Saturday, April 30, 2022, 03:08:32 PM EDT, Alexander Brandes ***@***.***> wrote:  
 
 


The change proposed makes sure your icons don't break on the next LTS baseline, because you aren't using the appropriate API but rely on path of the icon.
Considering views in Jenkins are commonly done in Jelly and not in Java, this change affects the appropriate Jelly file and no Java file.

**Pull request merged**
