### PR TITLE
Jenkins pipeline

### PR DESCRIPTION
**Pull request by zometer**
This is an update creating an "audit2db" pipeline step. The step can be added in any stage, but the database logging doesn't execute until the pipeline finish event. Let me know if you there's anything you want changed with the implementation.

### CODE REVIEW

**Comment by sergueik** [comment]
hello - 

Please give me  a few days, to test your PR. 

Happy holidays!

**Comment by zometer** [comment]
Any word on this?

**Comment by sergueik** [comment]
Sorry I forgot - Thanks for reminding - I was too busy at work - hope to be able to pass   smoke test build and merge this weekend ,and hope it not to turn into fool's day joke

Serguei Kouzmine
------ --------------------------------------
On Mon, 3/26/18, zometer <notifications@github.com> wrote:

 Subject: Re: [jenkinsci/audit2db-plugin] Jenkins pipeline (#23)
 To: "jenkinsci/audit2db-plugin" <audit2db-plugin@noreply.github.com>
 Cc: "Serguei Kouzmine" <kouzmine_serguei@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Monday, March 26, 2018, 3:00 PM
 
 Any word on this?
 
 —
 You are receiving this because you were
 mentioned.
 Reply to this
 email directly, view
 it on GitHub, or mute
 the thread.

**Comment by zometer** [comment]
*Bump*

**Pull request merged**
